import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import Header from "@/components/Header";
import TranstackQueryProvider from "@/components/TranstackQueryProvider";
import NextTopLoader from "nextjs-toploader";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Shop-24",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className + ' dark:bg-zinc-950'}>
                <NextTopLoader
                    color="#2563EB"
                    initialPosition={0.08}
                    crawlSpeed={200}
                    height={3}
                    crawl={true}
                    showSpinner={false}
                    easing="ease"
                    speed={200}
                    shadow="0 0 10px #2299DD,0 0 5px #2299DD"
                    zIndex={1600}
                    showAtBottom={false}
                />
                <TranstackQueryProvider>
                    <main className="max-w-[1440px] mx-auto px-6 w-[100%]">
                        <Header />
                        {children}
                    </main>
                </TranstackQueryProvider>

            </body>
        </html>
    );
}
