import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import Header from "@/components/Header";
import TranstackQueryProvider from "@/components/TranstackQueryProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Shop-24",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className + ' dark:bg-zinc-950'}>
                <TranstackQueryProvider>
                    <main className="max-w-[1440px] mx-auto px-6 w-[100%]">
                        <Header />
                        {children}
                    </main>
                </TranstackQueryProvider>

            </body>
        </html>
    );
}
