import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import Header from "@/components/Header";
import TranstackQueryProvider from "@/components/TranstackQueryProvider";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "MyAccount",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <TranstackQueryProvider>

                    <div className="flex items-center gap-5">

                        <div className="flex flex-col gap-3">
                            <Link href={"/my-account/orders"}>orders</Link>
                            <Link href={"/my-account/wishlist"}>wishlist</Link>
                            <Link href={"/orders"}>account-details</Link>
                            <Link href={"/orders"}>change-details</Link>
                        </div>

                        <div>
                            {children}
                        </div>

                    </div>
                </TranstackQueryProvider>

            </body>
        </html>
    );
}
